# Generated by Django 4.1.9 on 2023-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacyapps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicamentos",
            name="type",
        ),
        migrations.RemoveField(
            model_name="medicamentos",
            name="user",
        ),
        migrations.AddField(
            model_name="medicamentos",
            name="manufacturer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicamentos",
            name="price",
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicamentos",
            name="selectedAmount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
