# Generated by Django 4.2 on 2023-05-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapps', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pharmacyapps.user'),
        ),
    ]
