# Generated by Django 4.2 on 2023-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapps', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentos',
            name='type',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='user',
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='price',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='selectedAmount',
            field=models.IntegerField(null=True),
        ),
    ]
