# Generated by Django 4.2 on 2023-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapps', '0006_remove_medicamentos_type_remove_medicamentos_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PICKING_ITEMS', 'Picking Items'), ('NOT_STARTED', 'Not Started'), ('WAITING_CONFIRMATION', 'Waiting Confirmation')], default='NOT_STARTED', max_length=20)),
            ],
        ),
    ]
